version: 2
jobs:
  build:
    working_directory: ~/project
    machine: true

    steps:
      - checkout

      - restore_cache:
          key: circleci-java-sizebay-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: circleci-java-sizebay-{{ checksum "pom.xml" }}

      - run: ls ~/.m2/repository

      - run: git clone git@github.com:sizebay/Severino.git utils
      - run: mvn -s utils/sizebay-circleci/circle.maven-settings.xml -Dconfig.skip.tests=true clean package
      - run: mvn -s utils/sizebay-circleci/circle.maven-settings.xml clean test
      - run: sudo mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - run: sudo find . -type f -regex ".*/output/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;

  deploy-prod:
      machine: true
      working_directory: ~/project
      steps:
        - checkout
        - run: git clone git@github.com:sizebay/Severino.git utils
        - run:
            name: Deploy app in aws usaing maven
            command:  mvn -s utils/sizebay-circleci/circle.maven-settings.xml -Dconfig.skip.tests=true clean deploy

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy-prod:
          filters:
            branches:
              only: master