version: 2
jobs:
  build:
    working_directory: ~/project
    machine: true

    steps: # a collection of executable commands

      - checkout # check out source code to working directory
      - run : git clone git@github.com:sizebay/Severino.git utils

  test:
    machine: true
    steps:
      - checkout
      - run: mvn -s utils/sizebay-circleci/circle.maven-settings.xml clean test
      - run: sudo mkdir -p $CIRCLE_TEST_REPORTS/junit/
      - run: find . -type f -regex ".*/output/surefire-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
            requires:
              - build