package sizebay.catalog.client.model;

public enum ClothesType {
	FULL_BODY,
	BOTTOM,
	TOP,
	UNDERWEAR_FULL_BODY,
	UNDERWEAR_BOTTOM,
	UNDERWEAR_TOP,
	WETSUIT_FULL_BODY,
	WETSUIT_BOTTOM,
	WETSUIT_TOP,
	HEAD_ACCESSORY,
	HAND_WRIST_ACCESSORY,
	HAND_PALM_ACCESSORY,
	LEG_ACCESSORY,
	ARM_ACCESSORY;
}